DEFS		+= -DSTM32F4

INCLUDES += $(patsubst %,-I%, . $(SHARED_DIR))

LDSCRIPT = ../stm32-default.ld

OPENCM3_DIR	= ../libopencm3

OPENCM3_LIB = opencm3_stm32f4
OPENCM3_DEFS = -DSTM32F4
FP_FLAGS ?= -mfloat-abi=hard -mfpu=fpv4-sp-d16
ARCH_FLAGS = -mthumb -mcpu=cortex-m4 $(FP_FLAGS)

include ../Makefile.rules
